#!/usr/bin/env python3
"""Build data/actors/index.yml from actor profiles."""

from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
ACTOR_DIR = ROOT / "data" / "actors"
INDEX = ACTOR_DIR / "index.yml"


def main() -> int:
    actors = []
    for path in sorted(ACTOR_DIR.rglob("*.yml")):
        if path.name == "index.yml":
            continue
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        actors.append({
            "id": data.get("id"),
            "name": data.get("name"),
            "path": str(path.relative_to(ROOT)).replace("\\", "/"),
            "country": data.get("country"),
            "confidence": data.get("confidence"),
        })

    payload = {
        "note": "Generated by scripts/build_index.py",
        "actors": actors,
    }
    INDEX.write_text(yaml.safe_dump(payload, sort_keys=False, allow_unicode=True), encoding="utf-8")
    print(f"Wrote {INDEX.relative_to(ROOT)} with {len(actors)} actors")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
